# teams_dict = {
#     'Albania' : 'flag_al',
#     'Austria' : 'flag_at',
#     'Belgium' : 'flag_be',
#     'Croatia' : 'flag_hr',
#     'Czechia' : 'flag_cz',
#     'Denmark' : 'flag_dk',
#     'England' : 'england',
#     'France' : 'flag_fr',
#     'Georgia' : 'flag_ge',
#     'Germany' : 'flag_de',
#     'Hungary' : 'flag_hu',
#     'Italy' : 'flag_it',
#     'Netherlands' : 'flag_nl',
#     'Poland' : 'flag_pl',
#     'Portugal' : 'flag_pt',
#     'Romania' : 'flag_ro',
#     'Scotland' : 'scotland',
#     'Serbia' : 'flag_rs',
#     'Slovakia' : 'flag_sk',
#     'Slovenia' : 'flag_si',
#     'Spain' : 'flag_es',
#     'Switzerland' : 'flag_ch',
#     'Turkiye' : 'flag_tr',
#     'Ukraine' : 'flag_ua',
#     '' : 'grey_question'
# }

teams_dict = {
    'Algeria': 'flag_dz',
    'Argentina': 'flag_ar',
    'Australia': 'flag_au',
    'Austria': 'flag_at',
    'Belgium': 'flag_be',
    'Bosnia and Herzegovina': 'flag_ba',
    'Brazil': 'flag_br',
    'Canada': 'flag_ca',
    'Cape Verde': 'flag_cv',
    'Colombia': 'flag_co',
    'Croatia': 'flag_hr',
    'Curaçao': 'flag_cw',
    'Czechia': 'flag_cz',
    'DR Congo': 'flag_cd',
    'Ecuador': 'flag_ec',
    'Egypt': 'flag_eg',
    'England': 'england',
    'France': 'flag_fr',
    'Germany': 'flag_de',
    'Ghana': 'flag_gh',
    'Haiti': 'flag_ht',
    'Iran': 'flag_ir',
    'Iraq': 'flag_iq',
    'Ivory Coast': 'flag_ci',
    'Japan': 'flag_jp',
    'Jordan': 'flag_jo',
    'Mexico': 'flag_mx',
    'Morocco': 'flag_ma',
    'Netherlands': 'flag_nl',
    'New Zealand': 'flag_nz',
    'Norway': 'flag_no',
    'Panama': 'flag_pa',
    'Paraguay': 'flag_py',
    'Portugal': 'flag_pt',
    'Qatar': 'flag_qa',
    'Saudi Arabia': 'flag_sa',
    'Scotland': 'scotland',
    'Senegal': 'flag_sn',
    'South Africa': 'flag_za',
    'South Korea': 'flag_kr',
    'Spain': 'flag_es',
    'Sweden': 'flag_se',
    'Switzerland': 'flag_ch',
    'Tunisia': 'flag_tn',
    'Turkey': 'flag_tr',
    'United States': 'flag_us',
    'Uruguay': 'flag_uy',
    'Uzbekistan': 'flag_uz',
    '' : 'grey_question'
}